name: Publish Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 0 * * 2' # Weekly on Tuesday at 00:30

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/gitdags
          tags: latest
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: Dockerfile
